[profile.default]
src = 'contracts'
out = 'artifacts'
libs = ['lib']
solc_version = '0.8.28'
via_ir = true
optimize = true
optimizer_runs = 200
auto_detect_solc = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
